version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8009:8009"
    env_file:
      - .env
    depends_on:
      - db
      - ollama

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3100:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lexicare_db
      POSTGRES_USER: lexicare_user
      POSTGRES_PASSWORD: lexicare_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
